### ISSUE TITLE
Loader Issue

### ISSUE THREAD

**Issue by VishalChauhan525** [D-codE-Hub/Guide-to-Install-Frappe-ERPNext-in-Windows-Using-Docker#1]
Getting lot of Errors like this >>

09:33:49 watch.1    | ✘ [ERROR] No loader is configured for ".html" files: ../erpnext/erpnext/public/js/templates/call_link.html
09:33:49 watch.1    | 
09:33:49 watch.1    |     ../erpnext/erpnext/public/js/erpnext.bundle.js:23:7:
09:33:49 watch.1    |       23 │ import "./templates/call_link.html";

Please give me a solution for this.

**Comment by windowshopr** [comment]
I'm getting this, although running on Windows 10.

```
frappe@2f062f85a70b:/workspace/development/frappe-bench$ bench start
04:23:30 system     | web.1 started (pid=33739)
04:23:30 system     | schedule.1 started (pid=33745)
04:23:30 system     | watch.1 started (pid=33746)
04:23:30 system     | worker.1 started (pid=33744)
04:23:30 system     | socketio.1 started (pid=33747)
04:23:35 watch.1    | 
04:23:35 web.1      | /workspace/development/frappe-bench/apps/frappe/frappe/core/doctype/file/utils.py:2: DeprecationWarning: 'imghdr' is deprecated and slated for removal in Python 3.13
04:23:35 web.1      |   import imghdr
04:23:35 watch.1    | yarn run v1.22.22
04:23:35 watch.1    | $ node esbuild --watch --live-reload
04:23:36 socketio.1 | node:events:495
04:23:36 socketio.1 |       throw er; // Unhandled 'error' event
04:23:36 socketio.1 |       ^
04:23:36 socketio.1 | 
04:23:36 socketio.1 | Error: getaddrinfo ENOTFOUND redis-socketio
04:23:36 socketio.1 |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:108:26)
04:23:36 socketio.1 | Emitted 'error' event on RedisClient instance at:
04:23:36 socketio.1 |     at RedisClient.on_error (/workspace/development/frappe-bench/apps/frappe/node_modules/redis/index.js:342:14)
04:23:36 socketio.1 |     at Socket.<anonymous> (/workspace/development/frappe-bench/apps/frappe/node_modules/redis/index.js:223:14)
04:23:36 socketio.1 |     at Socket.emit (node:events:517:28)
04:23:36 socketio.1 |     at emitErrorNT (node:internal/streams/destroy:151:8)
04:23:36 socketio.1 |     at emitErrorCloseNT (node:internal/streams/destroy:116:3)
04:23:36 socketio.1 |     at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
04:23:36 socketio.1 |   errno: -3008,
04:23:36 socketio.1 |   code: 'ENOTFOUND',
04:23:36 socketio.1 |   syscall: 'getaddrinfo',
04:23:36 socketio.1 |   hostname: 'redis-socketio'
04:23:36 socketio.1 | }
04:23:36 socketio.1 | 
04:23:36 socketio.1 | Node.js v18.18.2
04:23:36 system     | socketio.1 stopped (rc=1)
04:23:36 system     | sending SIGTERM to web.1 (pid 33739)
04:23:36 system     | sending SIGTERM to watch.1 (pid 33746)
04:23:36 system     | sending SIGTERM to schedule.1 (pid 33745)
04:23:36 system     | sending SIGTERM to worker.1 (pid 33744)
04:23:36 system     | worker.1 stopped (rc=-15)
04:23:37 system     | schedule.1 stopped (rc=-15)
04:23:37 system     | web.1 stopped (rc=-15)
04:23:37 system     | watch.1 stopped (rc=-15)
```

**Comment by benjamen** [comment]
sudo apt update && sudo apt install supervisor. worked in me (basically install supervisor)
